// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Location {
  var latitude: Double
  var longitude: Double

  static func fromList(_ list: [Any?]) -> Location? {
    let latitude = list[0] as! Double
    let longitude = list[1] as! Double

    return Location(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Placemark {
  /// 位置
  var name: String
  /// 街道
  var thoroughfare: String
  /// 子街道
  var subThoroughfare: String
  /// 市
  var locality: String
  /// 区\县
  var subLocality: String
  /// 行政区
  var administrativeArea: String
  /// 国家
  var country: String

  static func fromList(_ list: [Any?]) -> Placemark? {
    let name = list[0] as! String
    let thoroughfare = list[1] as! String
    let subThoroughfare = list[2] as! String
    let locality = list[3] as! String
    let subLocality = list[4] as! String
    let administrativeArea = list[5] as! String
    let country = list[6] as! String

    return Placemark(
      name: name,
      thoroughfare: thoroughfare,
      subThoroughfare: subThoroughfare,
      locality: locality,
      subLocality: subLocality,
      administrativeArea: administrativeArea,
      country: country
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      thoroughfare,
      subThoroughfare,
      locality,
      subLocality,
      administrativeArea,
      country,
    ]
  }
}

private class LocationPlusCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return Location.fromList(self.readValue() as! [Any?])
      case 129:
        return Placemark.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class LocationPlusCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Location {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? Placemark {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LocationPlusCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LocationPlusCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LocationPlusCodecWriter(data: data)
  }
}

class LocationPlusCodec: FlutterStandardMessageCodec {
  static let shared = LocationPlusCodec(readerWriter: LocationPlusCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LocationPlus {
  func startUpdatingLocation() throws
  func stopUpdatingLocation() throws
  func requestSingleLocation(completion: @escaping (Result<Location, Error>) -> Void)
  func reverseGeo(location: Location, completion: @escaping (Result<[Placemark], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LocationPlusSetup {
  /// The codec used by LocationPlus.
  static var codec: FlutterStandardMessageCodec { LocationPlusCodec.shared }
  /// Sets up an instance of `LocationPlus` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LocationPlus?) {
    let startUpdatingLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.location_plus.LocationPlus.startUpdatingLocation", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startUpdatingLocationChannel.setMessageHandler { _, reply in
        do {
          try api.startUpdatingLocation()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startUpdatingLocationChannel.setMessageHandler(nil)
    }
    let stopUpdatingLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.location_plus.LocationPlus.stopUpdatingLocation", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopUpdatingLocationChannel.setMessageHandler { _, reply in
        do {
          try api.stopUpdatingLocation()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopUpdatingLocationChannel.setMessageHandler(nil)
    }
    let requestSingleLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.location_plus.LocationPlus.requestSingleLocation", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestSingleLocationChannel.setMessageHandler { _, reply in
        api.requestSingleLocation() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      requestSingleLocationChannel.setMessageHandler(nil)
    }
    let reverseGeoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.location_plus.LocationPlus.reverseGeo", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reverseGeoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let locationArg = args[0] as! Location
        api.reverseGeo(location: locationArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      reverseGeoChannel.setMessageHandler(nil)
    }
  }
}
