// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class Location {
  Location({
    required this.latitude,
    required this.longitude,
  });

  double latitude;

  double longitude;

  Object encode() {
    return <Object?>[
      latitude,
      longitude,
    ];
  }

  static Location decode(Object result) {
    result as List<Object?>;
    return Location(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }
}

class Placemark {
  Placemark({
    required this.name,
    required this.thoroughfare,
    required this.subThoroughfare,
    required this.locality,
    required this.subLocality,
    required this.administrativeArea,
    required this.country,
  });

  /// 位置
  String name;

  /// 街道
  String thoroughfare;

  /// 子街道
  String subThoroughfare;

  /// 市
  String locality;

  /// 区\县
  String subLocality;

  /// 行政区
  String administrativeArea;

  /// 国家
  String country;

  Object encode() {
    return <Object?>[
      name,
      thoroughfare,
      subThoroughfare,
      locality,
      subLocality,
      administrativeArea,
      country,
    ];
  }

  static Placemark decode(Object result) {
    result as List<Object?>;
    return Placemark(
      name: result[0]! as String,
      thoroughfare: result[1]! as String,
      subThoroughfare: result[2]! as String,
      locality: result[3]! as String,
      subLocality: result[4]! as String,
      administrativeArea: result[5]! as String,
      country: result[6]! as String,
    );
  }
}

class _LocationPlusCodec extends StandardMessageCodec {
  const _LocationPlusCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Location) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is Placemark) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return Location.decode(readValue(buffer)!);
      case 129:
        return Placemark.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LocationPlus {
  /// Constructor for [LocationPlus].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LocationPlus({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _LocationPlusCodec();

  Future<void> startUpdatingLocation() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.location_plus.LocationPlus.startUpdatingLocation';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopUpdatingLocation() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.location_plus.LocationPlus.stopUpdatingLocation';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Location> requestSingleLocation() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.location_plus.LocationPlus.requestSingleLocation';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as Location?)!;
    }
  }

  Future<List<Placemark?>> reverseGeo(Location location) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.location_plus.LocationPlus.reverseGeo';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[location]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<Placemark?>();
    }
  }
}
